### PR TITLE
Add functionality to watch state changes

### PR DESCRIPTION
**Pull request by mrkm4ntr**
## Why
I'd like to monitor the state of the circuit breaker using the gauge of Prometheus or something.

## Note
There is also a way that the user passes a callback, but I choose the current implementation  because the overall performance could be degraded by not being able to acquire a lock for a long time if the callback has a heavy processing. However, there is a downside that some changes are lost if the subscriber of the channel is slow.

### CODE REVIEW

**Comment by matope** [comment]
@mrkm4ntr Thank you for your proposal, and sorry to be late!
I think your approach is cool. But with this approach, only one receiver can consume all events because there is only one channel for events.

I think we have 2 options for this issue.
1. Manage multiple channels dynamically generated.
2. Invoke user-defined callback function in another goroutine.

What do you think about this?

**Comment by matope** [comment]
> There is also a way that the user passes a callback, but I choose the current implementation because the overall performance could be degraded by not being able to acquire a lock for a long time if the callback has a heavy processing. However, there is a downside that some changes are lost if the subscriber of the channel is slow.

Just calling the user-passed callback function might be good enough because it will give the user better handling about the event observing. If the user is performance-sensitive, they can use the buffered channel and design the policy on event dropping. Otherwise, they can do their tasks simply in the callback function.
This approach keeps relatively go-circuitbreaker's code clean. However, the user (who wants to write observing plugin) needs to write some more code. But the code will fit their needs.

**Comment by mrkm4ntr** [comment]
> Just calling the user-passed callback function might be good enough because it will give the user better handling about the event observing. If the user is performance-sensitive, they can use the buffered channel and design the policy on event dropping. Otherwise, they can do their tasks simply in the callback function.
This approach keeps relatively go-circuitbreaker's code clean. However, the user (who wants to write observing plugin) needs to write some more code. But the code will fit their needs.

Sounds good. I wanted to prevent users from degrading entire performance in any case. However, there may be cases where the user wants to prevent the event from being dropped.
I will rewrite this PR to invoke user-defined callbacks.

**Comment by mrkm4ntr** [comment]
Sorry for no actions for long time. I appreciate this function is already implemented in #13.

**Pull request closed without merging**
