### PR TITLE
Use functional options pattern for building the constructor

### PR DESCRIPTION
**Pull request by ervitis**
Hi! Great job about writing this circuit breaker pattern.
I have seen the library published by the golang weekly twitter account and I took a look at it. I think it could be great if it implements the functional options pattern* for building the circuitbreaker. The code would be very clean.

Please, don't hesitate to comment anything. 

Regards

* https://github.com/uber-go/guide/blob/master/style.md#functional-options

### CODE REVIEW

**Comment by matope** [comment]
Thank you for your contribution!

I'm +1 for adopting the Functional Options Pattern. It will make it easy to expand the config in the future without breaking change and also will be a user-friendly API. Even though it needs a breaking change, I think it is acceptable because this project is in the very beginning.

As for the options and namings, I have some proposals. (I'd like to have breaking change fewer times as much as possible.)

- Add optional functions like below
    - `WithTripByFailureCount(threshold int64) Option`
        -  which is an alias of `circuitbreaker.WithShouldTrip(circuitbreaker.NewTripFuncThreshold(10)),
` and unexport `NewTripFuncThreshold`.
    - `WithTripBySuccessiveFailures(threshold int64)`, same as above.
    - `WithTripByFailureRate(rate int64)`, same as above.
- Rename `WithShouldTrip` to `WithTripFunc`
- Rename `WithInterval` to `WithCounterResetInterval`
   - Because I have felt that "Options.Interval" was lack of explanation a little (Interval for what?), I want to add information to the name.
- Rename `WithTimeout` to `WithOpenTimeout`
- Rename `WithBackOff` to `WithOpenTimeoutBackOff`
- Unexport `Options` and the fields, and move comments to the option functions.

```go
	// sample of options
	cb := circuitbreaker.New(
		circuitbreaker.WithClock(clock.New()),
		circuitbreaker.WithFailOnContextCancel(true),
		circuitbreaker.WithFailOnContextDeadline(true),
		circuitbreaker.WithHalfOpenMaxSuccesses(10),
		circuitbreaker.WithOpenBackOff(backoff.NewExponentialBackOff()),
		circuitbreaker.WithOpenTimeout(10*time.Second),
		circuitbreaker.WithCounterResetInterval(10*time.Second),
		circuitbreaker.WithTripFunc(circuitbreaker.NewTripFuncThreshold(10)),
		circuitbreaker.WithTripByFailureCount(10),
		circuitbreaker.WithTripByConsecutiveFailure(10),
		circuitbreaker.WithTripByFailureRate(10, 0.9),
	)
```

@utahta (cc: @nguyengiabk ), I'd like to ask your opinion about this change.

**Comment by utahta** [comment]
I agree with your plan.
BTW, I think some settings should be `required` rather than `optional` because they are necessary for circuit breaker to work well.
Also, `WithClock` seems to be exported for testing. If so, we can remove it from options (maybe first step is to deprecate).

EDIT: I and matope-san discussed offline. And we are going to (maybe) reduce options step by step to make it clear what to set for circuit breaker.

**Comment by ervitis** [comment]
Great! I will review them after I finish work :)
Thank you so much

By the way, I had to edit some variables names in the tests because they were using the same name as the `clock` package

**Comment by matope** [comment]
@ervitis 
> By the way, I had to edit some variables names in the tests because they were using the same name as the clock package

Great, thanks!

**Comment by ervitis** [comment]
Also, I will add the `race` option in the tests, sorry I am mixing a lot of things in one branch

**Comment by ervitis** [comment]
About the function alias @matope, you meant these ones, isn't it?:

```go
func NewTripFuncThreshold(threshold int64) TripFunc {
	return func(cnt *Counters) bool { return cnt.Failures >= threshold }
}

func NewTripFuncConsecutiveFailures(threshold int64) TripFunc {
	return func(cnt *Counters) bool { return cnt.ConsecutiveFailures >= threshold }
}

func NewTripFuncFailureRate(min int64, rate float64) TripFunc {
	return func(cnt *Counters) bool {
		if cnt.Successes+cnt.Failures < min {
			return false
		}
		return float64(cnt.Failures)/float64(cnt.Successes+cnt.Failures) >= rate
	}
}
```

- The first function it passes one parameter, but it seems it doesn't need it.
- The third one it needs two parameters, is it correct?

**Comment by matope** [comment]
> The first function it passes one parameter, but it seems it doesn't need it.

Are you talking about the `threshold` argument, aren't you? If so, I think it works.
Could you tell me the reason why you think `NewTripFuncThreshold` doesn't need it?

```go
func NewTripFuncThreshold(threshold int64) TripFunc {
	return func(cnt *Counters) bool { return cnt.Failures >= threshold }
}
```

> The third one it needs two parameters, is it correct?
Yes, it is correct.

**Comment by ervitis** [comment]
Hi @matope, sorry I misunderstood your comment.
Ok, so the third function would be `WithTripByFailureRate(min int64, rate float64)`, is it ok?

Thank you so much!

**Comment by ervitis** [comment]
Some points:
- I had to create a function to return the `shouldTripFunc` data as a getter. Because the functional pattern returns an encapsulated object.
- Inside the `DefaultOpenBackoff()` method I had to rename the variable name because it colided with the `backoff` package name.
- In some tests, the `err` variable could be nil, and my Goland IDE showed it as a warning, so I put it inside a `if err != nil` block
- I have seen that there is a `panic()` instruction inside the `SetState()` method, should this function return an error instead a panic?

**Comment by matope** [comment]
@ervitis Thank you for your update & sorry to be late!

And sorry, this PR is getting too large for me to review. In order to focus on the original problem, could you separate fixes which are not related to functional options patterns into other PRs?

> I had to create a function to return the shouldTripFunc data as a getter. Because the functional pattern returns an encapsulated object.

I couldn't catch why we need the getter of tripFunc. Could you tell me the background of that?

> I have seen that there is a panic() instruction inside the SetState() method, should this function return an error instead a panic?

No, we don't have to return an error. For Circuit Breaker, only 3 states are defined. If you set an undefined state, we can panic. This is same situation as panic by zero-divide.

**Comment by ervitis** [comment]
Thank you @matope, yes you are right, sorry.

Because I cannot access to the shouldTripFunc for testing purpose, can you help me about those tests, please? :)

**Comment by matope** [comment]
> Because I cannot access to the shouldTripFunc for testing purpose, can you help me about those tests, please? :)

Sure thing:) In which test did you need to access to the func?

**Comment by ervitis** [comment]
Thank you so much!
In the `TestCircuitBreakerTripFuncs` test part

**Comment by matope** [comment]
I see. Because we unexported the definitions of TripFuncs, we can't test the functions themselves...

OK, let's not define following trip-helpers and back the TripFuncs exported.

- circuitbreaker.WithTripByFailureCount(10),
- circuitbreaker.WithTripByConsecutiveFailure(10),
- circuitbreaker.WithTripByFailureRate(10, 0.9),

**Comment by ervitis** [comment]
Thank you @matope, so I will revert the last change when I had to export those functions. So the three functions `newTripFuncThreshold`, `newTripFuncConsecutiveFailures` and `newTripFuncFailureRate` will be exported too I think, right?

**Comment by ervitis** [comment]
Sorry for the ping. Could we check this?

**Comment by matope** [comment]
@ervitis Sorry to be late. Yes, I think it's OK!

> So the three functions newTripFuncThreshold, newTripFuncConsecutiveFailures and newTripFuncFailureRate will be exported too I think, right?

**Comment by ervitis** [comment]
Cool! I think because we are in different timezones it's very difficult to coordinate, haha

それで今晩続けます

**Comment by ervitis** [comment]
Reverted!

**Comment by ervitis** [comment]
Any update on this?

**Comment by ervitis** [comment]
Hi, @matope, @utahta I think this will get into the limbo :smile:

**Comment by nerocrux** [comment]
Hi @ervitis sorry for the super late reply.

There are some changes that happened here, and I'm sorry to say that matope cannot maintain this repo for now.
Since it's a good piece of work and worth being well maintained, I hope me and my teammates can continue maintaining this repo instead.

I go through the conversation and the PR, I think the original requirements are being fulfilled and good to merge.
But it seems that there's a small conflict here, so I wonder if you can resolve it. After that, I'll merge it.

Thank you for your contribution and sorry again for the long wait.

**Comment by ervitis** [comment]
Hi @nerocrux, sure, no problem, I will review them and update the PR.

Thank you so much

**Comment by ervitis** [comment]
hi @nerocrux, I have updated and resolved the conflicts, but because the PR is old maybe some settings in the circleci file are deprecated. Can we update them using the github actions? I have some files I can re-use here to set the github actions module.

**Comment by nerocrux** [comment]
@ervitis Thank you for handling this.

> Can we update them using the github actions?

Sure! Let's do this.

> I have some files I can re-use here to set the github actions module.

That sounds great! Thanks!

**Comment by ervitis** [comment]
@nerocrux take a look when you have time. I think we need to setup the repository for stop using circleci and use github actions.

Also, I have added the function `WithOnStateChangeHookFn(hookFn StateChangeHook)` and fixed the tests

**Comment by nerocrux** [comment]
@ervitis Will do, thank you.

**Comment by ervitis** [comment]
I added the unit test and linter github actions. The linter is throwing some errors I think we should take a look at them

**Comment by ervitis** [comment]
Fixed all @nerocrux

**Comment by nerocrux** [comment]
@ervitis Thank you! LGTM!

Sorry again for mention this late, but can you split the shift circle CI to github actions part to a standalone PR? That will make it easier to confirm the behavior of github actions on this repo and keep this PR's purpose clear. 🙇

**Pull request merged**
